### ISSUE TITLE
SIGSEGV with DecodeAVFormat on WebM without sound

### ISSUE THREAD

**Issue by bakape** [Soreil/video#4]
Causes a segmentation violation, when passing a WebM without sound to DecodeAVFormat. 
To reproduce simply point https://github.com/Soreil/video/blob/master/detect_test.go#L8 to any such webm, like `webm/testdata/wafel.webm`. 

Can you reproduce? 

Trace: 

```
$ go test
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xfffffffd6fdc21b0 pc=0x4dcedb]

runtime stack:
runtime.throw(0x52b7a3, 0x2a)
    /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 18 [syscall, locked to thread]:
runtime.cgocall(0x4dd290, 0xc42003fd78, 0xc400000000)
    /usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc42003fd48 sp=0xc42003fd08
github.com/Soreil/video._Cfunc_extract_audio(0x2c01ce0, 0x0)
    ??:0 +0x4a fp=0xc42003fd78 sp=0xc42003fd48
github.com/Soreil/video.DecodeAVFormatDetail(0xc42089c000, 0x2dd0b8, 0x3ffe00, 0x2dd0b8, 0x3ffe00, 0x0, 0x0, 0x0, 0x0)
    /home/janis/go/src/github.com/Soreil/video/ffmpeg.go:351 +0x331 fp=0xc42003fe30 sp=0xc42003fd78
github.com/Soreil/video.TestDetectAVFormatDetail(0xc42008e240)
    /home/janis/go/src/github.com/Soreil/video/detect_test.go:34 +0xdc fp=0xc42003ff78 sp=0xc42003fe30
testing.tRunner(0xc42008e240, 0x533cf8)
    /usr/local/go/src/testing/testing.go:610 +0x81 fp=0xc42003ffa0 sp=0xc42003ff78
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42003ffa8 sp=0xc42003ffa0
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:646 +0x2ec

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42008e0c0, 0x52816f, 0x18, 0x533cf8, 0xc42004fd01)
    /usr/local/go/src/testing/testing.go:647 +0x316
testing.RunTests.func1(0xc42008e0c0)
    /usr/local/go/src/testing/testing.go:793 +0x6d
testing.tRunner(0xc42008e0c0, 0xc42003ae30)
    /usr/local/go/src/testing/testing.go:610 +0x81
testing.RunTests(0x533d88, 0x7a1000, 0x2, 0x2, 0x8)
    /usr/local/go/src/testing/testing.go:799 +0x2f5
testing.(*M).Run(0xc42003aef8, 0x7b63c0)
    /usr/local/go/src/testing/testing.go:743 +0x85
main.main()
    github.com/Soreil/video/_test/_testmain.go:56 +0xc6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
exit status 2
FAIL    github.com/Soreil/video 0.103s
```

**Comment by Soreil** [comment]
Can't reproduce under MinGW on Windows with FFMPEG 2.8.2 and Go 1.6, going to try on a more modern platform.

**Comment by Soreil** [comment]
Also seems to work on FFMPEG 3.0 and Go 1.7, going to try looking at what could cause this crash.

**Comment by bakape** [comment]
I'll try compiling a minimal ffmpeg 3.1 and see if that solves it.

**Comment by Soreil** [comment]
Let me retry to match your bug since this crash is reasonable

**Comment by Soreil** [comment]
Sorry, I misread your opening post and was not actually testing your bug. This one does exist.

**Comment by Soreil** [comment]
Bug should be fixed, can you verify on your end? If so I'll close this issue.

**Comment by bakape** [comment]
Fixed on my end too.
