### ISSUE TITLE
Crash on webm thumbnailing

### ISSUE THREAD

**Issue by bakape** [Soreil/video#6]
Trying to scale this webm results in panic https://mega.nz/#!RQ9SCITD!U5JwAzdWTFE_JDcjQpR2t5z_FlR6csDHk8U13W-fBQo

I have not looked too deeply into this yet. Could be a bug in the resize package, but for now I'll assume it's in the video package. 

Reproduction script: 

```
package main

import (
    "image"
    "os"

    "github.com/Soreil/imager"
)

func main() {
    file, err := os.Open("with no survivors.webm")
    if err != nil {
        panic(err)
    }
    defer file.Close()
    _, _, _, err = imager.Thumbnail(file, image.Point{150, 150})
    if err != nil {
        panic(err)
    }
}
```

Trace:

```
goroutine 1 [running]:
panic(0x528dc0, 0xc42000c140)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/nfnt/resize.imageYCbCrToYCC(0xc420018100, 0xa)
    /home/janis/go/src/github.com/nfnt/resize/ycc.go:191 +0x424
github.com/nfnt/resize.Resize(0x96, 0x54, 0x7de820, 0xc420018100, 0x1, 0x55db08, 0xc420096000)
    /home/janis/go/src/github.com/nfnt/resize/resize.go:173 +0x3a89
github.com/nfnt/resize.Thumbnail(0x96, 0x96, 0x7de820, 0xc420018100, 0x1, 0xffffffffffffffff, 0xffffffffffffffff)
    /home/janis/go/src/github.com/nfnt/resize/thumbnail.go:54 +0xf8
github.com/Soreil/imager.Scale(0x7de820, 0xc420018100, 0x96, 0x96, 0x179, 0x4)
    /home/janis/go/src/github.com/Soreil/imager/main.go:39 +0x52
github.com/Soreil/imager.Thumbnail(0x7dd4e0, 0xc42002e078, 0x96, 0x96, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55db10, ...)
    /home/janis/go/src/github.com/Soreil/imager/main.go:55 +0xfb
main.main()
    /home/janis/src/with no survivors.go:16 +0xaa
```

**Comment by Soreil** [comment]
Going to give it a look this evening, thanks for reporting.

**Comment by Soreil** [comment]
There is an off by one error either in the standard library or the video package, if I try to encode leaving one pixel off it works. I'll check what causes it.
Simply printing the image.Image as image.YCbCr leads to an out of range error, interesting. It's on our end.

**Comment by bakape** [comment]
I just remembered an old chrome issue with uneven pixel dimention Webm. So then I found this https://groups.google.com/a/webmproject.org/forum/m/#!topic/webm-discuss/LaCKpqiDTXM

I am positive that is our cause, so can this be fixed soon? Crashing servers is never good.

**Comment by Soreil** [comment]
Looks like a reasonable cause and solution, expect a fix today if it is correct. Thanks for finding it.

**Comment by Soreil** [comment]
Pushed a temp fix for now, the solution on the linked post is correct in spirit but I have not yet found where to make the offset. If I have to lose a pixel to the right I guess that's fine but not ideal.

**Comment by bakape** [comment]
Okay, as long as there aren't crashes.
